# Generated by Django 4.2.1 on 2023-05-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('nome', models.CharField(max_length=100)),
                ('documento_identidade', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peca', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
